import { FinancialFormData } from '../types/financial';

export const SAMPLE_PROFILE_STANDARD: FinancialFormData = {
  income: {
    employmentType: 'salaried',
    annualGrossIncome: 85000,
    hourlyWage: 0,
    hoursPerWeek: 40,
    payFrequency: 'biweekly',
    bonusCommission: 3000,
    otherIncome: 0,
    state: 'TX',
    filingStatus: 'single',
  },
  housingTransport: {
    rentOrMortgage: 1650,
    utilities: 220,
    homeInsurance: 35,
    propertyTax: 0,
    carPayment: 380,
    carInsurance: 130,
    fuel: 140,
    publicTransit: 0,
    parkingTolls: 30,
    maintenance: 60,
  },
  livingExpenses: {
    foodGroceries: 450,
    restaurants: 250,
    healthcare: 120,
    phone: 75,
    internet: 65,
    subscriptions: 45,
    entertainment: 120,
    shopping: 150,
    childcare: 0,
    education: 0,
    personalCare: 80,
    otherExpenses: 60,
    customExpenses: [
      { id: 'c1', category: 'Fitness', description: 'Gym & Climbing Gym', amount: 95 },
    ],
  },
  debtSavings: {
    creditCardPayments: 150,
    studentLoans: 280,
    personalLoans: 0,
    otherDebt: 0,
    currentSavings: 14500,
    monthlySavings: 400,
    emergencyFundMonthly: 200,
    retirementMonthly: 350,
  },
};

export const SAMPLE_PROFILE_FAMILY: FinancialFormData = {
  income: {
    employmentType: 'multiple',
    annualGrossIncome: 135000,
    hourlyWage: 0,
    hoursPerWeek: 40,
    payFrequency: 'semimonthly',
    bonusCommission: 8000,
    otherIncome: 4800,
    state: 'CA',
    filingStatus: 'married_joint',
  },
  housingTransport: {
    rentOrMortgage: 2900,
    utilities: 380,
    homeInsurance: 110,
    propertyTax: 350,
    carPayment: 540,
    carInsurance: 220,
    fuel: 260,
    publicTransit: 75,
    parkingTolls: 40,
    maintenance: 120,
  },
  livingExpenses: {
    foodGroceries: 850,
    restaurants: 350,
    healthcare: 280,
    phone: 140,
    internet: 90,
    subscriptions: 65,
    entertainment: 200,
    shopping: 300,
    childcare: 650,
    education: 150,
    personalCare: 120,
    otherExpenses: 150,
    customExpenses: [],
  },
  debtSavings: {
    creditCardPayments: 200,
    studentLoans: 450,
    personalLoans: 0,
    otherDebt: 0,
    currentSavings: 38000,
    monthlySavings: 700,
    emergencyFundMonthly: 400,
    retirementMonthly: 850,
  },
};

export const INITIAL_EMPTY_FORM_DATA: FinancialFormData = {
  income: {
    employmentType: 'salaried',
    annualGrossIncome: 70000,
    hourlyWage: 35,
    hoursPerWeek: 40,
    payFrequency: 'biweekly',
    bonusCommission: 0,
    otherIncome: 0,
    state: 'TX',
    filingStatus: 'single',
  },
  housingTransport: {
    rentOrMortgage: 1400,
    utilities: 180,
    homeInsurance: 30,
    propertyTax: 0,
    carPayment: 320,
    carInsurance: 110,
    fuel: 120,
    publicTransit: 0,
    parkingTolls: 0,
    maintenance: 50,
  },
  livingExpenses: {
    foodGroceries: 400,
    restaurants: 180,
    healthcare: 100,
    phone: 65,
    internet: 60,
    subscriptions: 35,
    entertainment: 100,
    shopping: 120,
    childcare: 0,
    education: 0,
    personalCare: 60,
    otherExpenses: 50,
    customExpenses: [],
  },
  debtSavings: {
    creditCardPayments: 100,
    studentLoans: 250,
    personalLoans: 0,
    otherDebt: 0,
    currentSavings: 8500,
    monthlySavings: 300,
    emergencyFundMonthly: 150,
    retirementMonthly: 250,
  },
};

export const DEFAULT_FORM_DATA = INITIAL_EMPTY_FORM_DATA;

